# This file was generated by the {rix} R package v0.15.8 on 2025-04-14
# with following call:
# >rix(date = "2025-03-10",
#  > r_pkgs = c("arrow",
#  > "codetools",
#  > "conflicted",
#  > "countrycode",
#  > "dotenv",
#  > "dplyr",
#  > "geoarrow",
#  > "geodata",
#  > "terra",
#  > "wk",
#  > "quarto"),
#  > git_pkgs = list(list(package_name = "rixpress",
#  > repo_url = "https://github.com/b-rodrigues/rixpress",
#  > commit = "HEAD"),
#  > list(package_name = "sds",
#  > repo_url = "https://github.com/hypertidy/sds",
#  > commit = "aebd9f49fcec72b0767cb3328dae665125ac5860"),
#  > list(package_name = "dsn",
#  > repo_url = "https://github.com/hypertidy/dsn",
#  > commit = "15743da3a6c892f6654a3deab707425f86cabe98")),
#  >      ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.4.3")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-03-10.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      arrow
      codetools
      conflicted
      countrycode
      dotenv
      dplyr
      geoarrow
      geodata
      quarto
      terra
      wk;
  };
 
    dsn = (pkgs.rPackages.buildRPackage {
      name = "dsn";
      src = pkgs.fetchgit {
        url = "https://github.com/hypertidy/dsn";
        rev = "15743da3a6c892f6654a3deab707425f86cabe98";
        sha256 = "sha256-CGx7tXwEpm39r3iyjtTjWYfQGiObiAdii6NJgQA/0J4=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) ;
      };
    });

    rixpress = (pkgs.rPackages.buildRPackage {
      name = "rixpress";
      src = pkgs.fetchgit {
        url = "https://github.com/b-rodrigues/rixpress";
        rev = "HEAD";
        sha256 = "sha256-viyNy4+sEFkO+sf8lD3WhY1mgK9+8IXxUptUlPyhl28=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          igraph
          jsonlite
          processx;
      };
    });

    sds = (pkgs.rPackages.buildRPackage {
      name = "sds";
      src = pkgs.fetchgit {
        url = "https://github.com/hypertidy/sds";
        rev = "aebd9f49fcec72b0767cb3328dae665125ac5860";
        sha256 = "sha256-a4Jf97TQj5iE9p9q9tGKgznVwyrSiZQzMLH0i5YP8HM=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          countrycode
          tibble;
      };
    });
     
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R
      quarto
      which
      pandoc;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [ rixpress sds dsn rpkgs   system_packages   ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
