# This file was generated by the {rix} R package v0.16.1 on 2025-05-04
# with following call:
# >rix(date = "2025-04-29",
#  > r_pkgs = c("readr",
#  > "dplyr",
#  > "ggplot2",
#  > "brms",
#  > "quarto"),
#  > system_pkgs = "cmdstan",
#  > git_pkgs = list(list(package_name = "cmdstanr",
#  > repo_url = "https://github.com/stan-dev/cmdstanr",
#  > commit = "79d37792d8e4ffcf3cf721b8d7ee4316a1234b0c"),
#  > list(package_name = "rixpress",
#  > repo_url = "https://github.com/b-rodrigues/rixpress",
#  > commit = "HEAD")),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.5.0")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-04-29.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      brms
      dplyr
      ggplot2
      quarto
      readr;
  };
 
    cmdstanr = (pkgs.rPackages.buildRPackage {
      name = "cmdstanr";
      src = pkgs.fetchgit {
        url = "https://github.com/stan-dev/cmdstanr";
        rev = "79d37792d8e4ffcf3cf721b8d7ee4316a1234b0c";
        sha256 = "sha256-0994a3a4YNeaK73XYpxrC5blZyLkTHosQz1szxfVlyU=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          checkmate
          data_table
          jsonlite
          posterior
          processx
          R6
          withr
          rlang;
      };
    });

    rixpress = (pkgs.rPackages.buildRPackage {
      name = "rixpress";
      src = pkgs.fetchgit {
        url = "https://github.com/b-rodrigues/rixpress";
        rev = "HEAD";
        sha256 = "sha256-EgCmTo8hgbI4tBofzcMPSMvANAo7tCXlrepTo3eCwXY=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          igraph
          jsonlite
          processx;
      };
    });
     
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      cmdstan
      glibcLocales
      nix
      R
      quarto
      which
      pandoc;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ cmdstanr rixpress rpkgs   system_packages   ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
