# This file was generated by the {rix} R package v0.17.2 on 2025-10-20
# with following call:
# >rix(date = "2025-10-14",
#  > r_pkgs = c("ggplot2",
#  > "dplyr",
#  > "arrow",
#  > "rix",
#  > "rixpress",
#  > "quarto"),
#  > py_conf = list(py_version = "3.13",
#  > py_pkgs = c("pandas",
#  > "scikit-learn",
#  > "xgboost",
#  > "pyarrow",
#  > "ryxpress")),
#  > jl_conf = list(jl_version = "lts",
#  > jl_pkgs = c("Distributions",
#  > "DataFrames",
#  > "Arrow",
#  > "Random")),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.5.1")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-10-14.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      arrow
      dplyr
      ggplot2
      quarto
      rix
      rixpress;
  };
   
  pyconf = builtins.attrValues {
    inherit (pkgs.python313Packages) 
      pip
      ipykernel
      pandas
      pyarrow
      ryxpress
      scikit-learn
      xgboost;
  };
 
  jlconf = pkgs.julia-lts.withPackages [ 
      "Arrow"
      "DataFrames"
      "Distributions"
      "Random"
  ];
  
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      python313
      R
      quarto
      which
      pandoc;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    RETICULATE_PYTHON = "${pkgs.python313}/bin/python";

    buildInputs = [ rpkgs pyconf jlconf system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
